on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build & deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install

      - name: Migrate
        run: php artisan migrate

      - name: Deploy files to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'root'
          server: ${{ secrets.SERVER_IP }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: '/var/www/html/webbee-hackathon'
          sftpArgs: '-o ConnectTimeout=5'
